name: Super-Linter
on: push

jobs:
  Super_Linter:
    runs_on:ubuntu-latest
    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
      
    - name: install flake8
      run: pip install flake8
        
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
